export const dummyUsers = [
    {
        id: 1,
      fullName: 'John Doe',
      avatar: 'avatar1.jpg',
      phoneNo: '1234567890',
      email: 'john@example.com',
      password: 'password123',
      gender: 'male',
      age: 30,
      sportsInterest: ['Football', 'Basketball'],
      location: 'New York, USA',
      preferredSportActivities: ['Running', 'Swimming'],
      skillLevels: 'intermediate',
    },
    {
        id:2,
      fullName: 'Jane Smith',
      avatar: 'avatar2.jpg',
      phoneNo: '9876543210',
      email: 'jane@example.com',
      password: 'password456',
      gender: 'female',
      age: 25,
      sportsInterest: ['Tennis', 'Golf'],
      location: 'Los Angeles, USA',
      preferredSportActivities: ['Yoga', 'Cycling'],
      skillLevels: 'professional',
    },
  ];